In [1]:
from aux_conta import *
from glob import glob as gb

In [2]:
# archivos_tex = encontrar_archivos_tex(ruta)
file='../tex_es/05.vf5_result02_tp.tex'
palabra = r"\cite"              # Palabra clave a buscar        
cuenta(palabra,file)

🔍 Buscando: "\cite"
📄 Archivos .tex encontrados: 1
🔤 Case sensitive: No
--------------------------------------------------
  ⚠️  Error leyendo ../tex_es/05.vf5_result02_tp.tex: [Errno 2] No such file or directory: '../tex_es/05.vf5_result02_tp.tex'
--------------------------------------------------
📊 TOTAL: 0 ocurrencias de "\cite"
   (1 archivos sin coincidencias)

In [3]:
# === USO ===
file = '../tex_es/05.vf5_result02_tp.tex'
extraer_citas(file)

⚠️  Error leyendo ../tex_es/05.vf5_result02_tp.tex: [Errno 2] No such file or directory: '../tex_es/05.vf5_result02_tp.tex'

In [4]:
# === USO ===
comparar_citas(
    '../tex_es/01.vf7_introducao.tex',      # versión anterior
    '../tex_es/01.vr5_introducao.tex'    # versión nueva
)

📄 Viejo: 01.vf7_introducao.tex
📄 Nuevo: 01.vr5_introducao.tex
--------------------------------------------------
➖ AUTORES ELIMINADOS (7):
     blanchard2021warm
     gozzo2014subtropical
     gramcianinov2024early
     hannachi2007empirical
     oertel2021warm
     sinclair1997objective
     zscheischler2018future

➕ AUTORES AGREGADOS (9):
     bitencourt2010relating
     dalanhese2023new
     gan1991surface
     jones1993climatology
     kaylee2025convection
     kodama2019perspective
     padilhareinke2024objective
     simmonds1999southern
     sun2022evaluation

In [5]:
# === USO ===
comparar_citas_con_cantidad(
    '../tex_es/01.vf7_introducao.tex',      # versión anterior
    '../tex_es/01.vr5_introducao.tex'    # versión nueva
)

📄 Viejo: 01.vf7_introducao.tex
📄 Nuevo: 01.vr5_introducao.tex
--------------------------------------------------
  ➕ bitencourt2010relating: 0 → 1  (nuevo)
  ➖ blanchard2021warm: 1 → 0  (eliminado)
  ✏️  coutodesouza2024new: 4 → 2  (-2)
  ✏️  crespo2020potential: 2 → 1  (-1)
  ➕ dalanhese2023new: 0 → 1  (nuevo)
  ➕ gan1991surface: 0 → 1  (nuevo)
  ➖ gozzo2014subtropical: 1 → 0  (eliminado)
  ➖ gramcianinov2024early: 1 → 0  (eliminado)
  ➖ hannachi2007empirical: 1 → 0  (eliminado)
  ➕ jones1993climatology: 0 → 1  (nuevo)
  ➕ kaylee2025convection: 0 → 1  (nuevo)
  ➕ kodama2019perspective: 0 → 1  (nuevo)
  ➖ oertel2021warm: 1 → 0  (eliminado)
  ➕ padilhareinke2024objective: 0 → 1  (nuevo)
  ✏️  priestley2022improved: 2 → 1  (-1)
  ✏️  reboita2010south: 2 → 1  (-1)
  ✏️  reboita2022from: 3 → 2  (-1)
  ✏️  reboita2026meteorology: 2 → 4  (+2)
  ➕ simmonds1999southern: 0 → 1  (nuevo)
  ✏️  sinclair1994objective: 2 → 1  (-1)
  ➖ sinclair1997objective: 1 → 0  (eliminado)
  ➕ sun2022evaluation: 0 → 1  (nuevo)
  ➖ zscheischler2018future: 1 → 0  (eliminado)
--------------------------------------------------
📊 Total citas viejo: 56
📊 Total citas nuevo: 53

In [7]:
archivos = gb('../tex_es/*vr*.tex')
buscar_autor_en_archivos(sorted(archivos), 'sinclair2023relationship')

🔍 Buscando: "sinclair2023relationship"
📂 Archivos analizados: 10
🔤 Case sensitive: No
------------------------------------------------------------
✅ Encontrado en 3 archivo(s)

  📄 05.vr2_result02_tp.tex
     → Línea 19: \citet{sinclair2023relationship}
     → Línea 25: \citep{sinclair2023relationship}
     📊 Total: 2
  📄 01.vr5_introducao.tex
     → Línea 34: \citet{sinclair2023relationship}
     📊 Total: 1
  📄 04.vr2_result01_w10.tex
     → Línea 254: \citep{sinclair2023relationship}
     📊 Total: 1
------------------------------------------------------------
📊 TOTAL: 4 ocurrencias en 3 archivo(s)

{'01.vr5_introducao.tex': {'count': 1,
  'ocurrencias': [{'linea': 34,
    'cita_completa': '\\citet{sinclair2023relationship}'}]},
 '04.vr2_result01_w10.tex': {'count': 1,
  'ocurrencias': [{'linea': 254,
    'cita_completa': '\\citep{sinclair2023relationship}'}]},
 '05.vr2_result02_tp.tex': {'count': 2,
  'ocurrencias': [{'linea': 19,
    'cita_completa': '\\citet{sinclair2023relationship}'},
   {'linea': 25, 'cita_completa': '\\citep{sinclair2023relationship}'}]}}

In [47]:
import pandas as pd
from buscar_keywords import search_keywords_in_bib
# Una palabra
lista=['wind',"cyclone", "extratropical", "EOF"]
df = search_keywords_in_bib(
    "../tex_es/bibliografia_vr1.bib", 
    lista,
    
)

In [48]:
df.sort_values(lista[:1], ascending=False)

                            autor  wind  cyclone  extratropical  EOF
32            gentile2023observed    17        4              0    0
64     laurila2021characteristics    14       10              8    0
78   eisenstein2023identification    10        7              1    0
22             chen2024evaluation     8        1              1    0
31           stankovic2025surface     7        3              0    0
..                            ...   ...      ...            ...  ...
19           dacre2023climatology     0       12              1    0
70       reboita2018extratropical     0        8              1    0
71               rocha2016estudio     0        0              0    0
41            hersbach_era5_2023b     0        0              0    0
104            coll2024lagrangian     0        1              1    0

[105 rows x 5 columns]

In [49]:
df[df['EOF'] > 0].sort_values('EOF', ascending=False)

                             autor  wind  cyclone  extratropical  EOF
14               sun2022evaluation     0        0              0   14
94           hannachi2007empirical     0        0              0    8
98         sasaki2021intraseasonal     4        5              2    6
29                 rieger2024xeofs     0        0              0    3
92   bretherton1992intercomparison     0        0              0    3
86           liang2018multivariate     0        0              0    2
80                    vera2002cold     0        3              1    1
99                 hannachi2023eof     0        0              0    1
103            miranda2026patterns     2        1              1    1